name: package-ui

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev*'
      - 'features/*'
    paths:
      - 'src/RedDog.UI/**'

  workflow_dispatch:

env:
  PROJECT: UI
  REPOSITORY: reddog
  IMAGE: ui

jobs:
  environment:
    name: Determine Environment Name
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.environment.outputs.name }}

    steps:
      - name: Set Environment Name
        id: environment
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "::set-output name=name::Production"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ] || [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "::set-output name=name::Test"
          else
             echo "::set-output name=name::Features"
          fi         

  build:
    name: Build Service
    runs-on: ubuntu-latest
    needs: environment
    environment: 
      name: ${{ needs.environment.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build Image
        run: |
          az acr build --registry $REGISTRY \
                       --resource-group $RESOURCE_GROUP \
                       --image ${REPOSITORY}/${IMAGE}:latest \
                       --image ${REPOSITORY}/${IMAGE}:$(echo ${GITHUB_SHA} | cut -c1-7) \
                       ./src/RedDog.${PROJECT}
        env:
          REGISTRY: acr${{ secrets.AZURE_PROJECT_NAME }}${{ secrets.AZURE_UNIQUE_CODE }}
          RESOURCE_GROUP: ${{ needs.environment.outputs.name }}-${{ secrets.AZURE_PROJECT_NAME }}-${{ secrets.AZURE_UNIQUE_CODE }}

