name: package-accounting-service

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev*'
      - 'features/*'
    paths:
      - 'src/RedDog.AccountingService/**'

  workflow_dispatch:

jobs:
  environment:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.main.outputs.version }}
      created: ${{ steps.main.outputs.created }}
      project: ${{ steps.main.outputs.project }}
      image: ${{ steps.main.outputs.image }}
      repository: ${{ steps.main.outputs.repository }}  
    steps:
      - id: main
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo ::set-output name=name::Production
          elif [ "${{ github.ref }}" = "refs/heads/dev" ] || [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo ::set-output name=name::Test
          else
             echo ::set-output name=name::Features
          fi         
          echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-7)
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=project::AccountingService
          echo ::set-output name=repository::reddog
          echo ::set-output name=image::accounting-service

  build:
    name: Build Service
    runs-on: ubuntu-latest
    needs: environment
    environment: 
      name: ${{ needs.environment.outputs.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build Accounting Service
        run: |
          az acr build --registry $REGISTRY \
                       --name $RESOURCE_GROUP \
                       --image ${{ needs.environment.outputs.repository }}/${{ needs.environment.outputs.image }}:latest \
                       --image ${{ needs.environment.outputs.repository }}/${{ needs.environment.outputs.image }}:${{ needs.environment.outputs.version }} \
                       --file ./src/RedDog.${{ needs.environment.outputs.project }}/Dockerfile ./src
        env:
          REGISTRY: acr${{ secrets.AZURE_PROJECT_NAME }}${{ secrets.AZURE_UNIQUE_CODE }}
          RESOURCE_GROUP: ${{ needs.environment.outputs.name }}-${{ secrets.AZURE_PROJECT_NAME }}-${{ secrets.AZURE_UNIQUE_CODE }}

