# This workflow provisions the infrastructure

name: Provision Infrastructure

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
      - main
      - develop
      - features/*
    paths:
      - "./infra/**"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "./infra/**"
  workflow_dispatch:
  
# https://github.com/Azure/login#sample-workflow-that-uses-azure-login-action-using-oidc-to-run-az-cli-linux
permissions:
      id-token: write
      contents: read

jobs:

  environment:
    name: Determine Environment Name
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.environment.outputs.name }}

    steps:
      - name: Set Environment Name
        id: environment
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "::set-output name=name::Production"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ] || [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "::set-output name=name::Test"
          else
             echo "::set-output name=name::Features"
          fi         

  validate:
    needs: [environment]
    name: Validate Environment Secrets
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.environment.outputs.name }}

    steps:          
      - name: Set Environment Suffix
        id: suffix
        run: |
          if [ "${{ secrets.AZURE_PROJECT_NAME }}" == "" ]; then
            echo "Please set environment secret 'AZURE_PROJECT_NAME' before running this workflow"
            exit 1
          fi
          if [ "${{ secrets.AZURE_UNIQUE_CODE }}" == "" ]; then
            echo "Please set environment secret 'AZURE_UNIQUE_CODE' before running this workflow"
            exit 1
          fi
  
  group:
    needs: [environment, validate]
    name: Provision Resource Group 
    runs-on: ubuntu-latest
    environment: 
      name: ${{ needs.environment.outputs.name }}

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Group
        run: |
          if [ "${{ secrets.AZURE_RESOURCE_GROUP }}" == "" ]; then
            if [ "${{ secrets.AZURE_LOCATION }}" == "" ]; then
              echo "Please set environment secret 'AZURE_LOCATION' before running this workflow"
              exit 1
            fi
            RESOURCEGROUPNAME=`az group create --name ${{ needs.environment.outputs.name }}-${{ secrets.AZURE_PROJECT_NAME }}-${{ secrets.AZURE_UNIQUE_CODE }} --location ${{ secrets.AZURE_LOCATION }} --query name | xargs`
          else
            RESOURCEGROUPNAME=`az group show --name ${{ secrets.AZURE_RESOURCE_GROUP }} --query name | xargs`
          fi

          echo "::set-output name=name::${RESOURCEGROUPNAME}"     
